# Default values. These can be overridden by the config file ~/.config/noa/noa.toml
# or ~/.noa.toml.
key_bindings = [
    { scope = "buffer", key = "k", modifiers = ["ctrl"], action = "truncate" },
    { scope = "buffer", key = "s", modifiers = ["ctrl"], action = "save" },
    { scope = "buffer", key = "f", modifiers = ["ctrl"], action = "open_finder" },
]

# Based on One Dark Pro theme
# https://github.com/Binaryify/OneDark-Pro
[theme]
"buffer.find_match" = { bg = "grey" }
"buffer.current_line" = { bg = "grey" }
"buffer.line_status" = { fg = "grey" }
"buffer.flash" = { fg = "grey" }
"buffer.matching_bracket" = { bg = "grey", bold = true }

"line_status.modified" = { bg = "grey" }
"line_status.added" = { bg = "grey" }
"line_status.deleted" = { bg = "grey" }

"prompt.name" = { bg = "grey", bold = true }
"meta_line.background" = { bg = "grey" }

"selector.input" = { fg = "grey" }
"selector.selected" = { fg = "grey" }

"notification.warn" = { fg = "grey" }
"notification.info" = { fg = "grey" }
"notification.error" = { fg = "grey" }

"completion.item" = { bg = "grey" }
"completion.selected" = { bg = "grey" }

"syntax.boolean" = { fg = "grey" }
"syntax.conditional" = { fg = "grey" }
"syntax.constant" = { fg = "grey" }
"syntax.constant.builtin" = { fg = "grey" }
"syntax.field" = { fg = "grey" }
"syntax.float" = { fg = "grey" }
"syntax.function" = { fg = "green" }
"syntax.include" = { fg = "grey" }
"syntax.keyword.function" = { fg = "magenta" }
"syntax.keyword.operator" = { fg = "magenta" }
"syntax.keyword.return" = { fg = "magenta" }
"syntax.label" = { fg = "grey" }
"syntax._name" = { fg = "grey" }
"syntax.namespace" = { fg = "grey" }
"syntax.none" = { fg = "grey" }
"syntax.number" = { fg = "grey" }
"syntax.operator" = { fg = "grey" }
"syntax.parameter" = { fg = "grey" }
"syntax.property" = { fg = "grey" }
"syntax.punctuation.bracket" = { fg = "grey" }
"syntax.punctuation.delimiter" = { fg = "grey" }
"syntax.punctuation.special" = { fg = "grey" }
"syntax.repeat" = { fg = "grey" }
"syntax.string" = { fg = "green" }
"syntax.string.escape" = { fg = "grey" }
"syntax.string.special" = { fg = "grey" }
"syntax.text.emphasis" = { fg = "grey" }
"syntax.text.literal" = { fg = "grey" }
"syntax.text.strong" = { fg = "grey" }
"syntax.text.title" = { fg = "grey" }
"syntax.type" = { fg = "green" }
"syntax.type.builtin" = { fg = "grey" }
"syntax.value" = { fg = "grey" }
"syntax.variable" = { fg = "grey" }
"syntax.variable.builtin" = { fg = "grey" }

[colors]
