# Based on One Dark Pro theme
# https://github.com/Binaryify/OneDark-Pro
[theme]
"keyword" = { fg = "purple" }
"variable" = { fg = "deepRed" }
"string" = { fg = "green" }

"buffer.find_match" = { bg = "chalky" }
"buffer.current_line" = { bg = "lightgrey" }
"buffer.line_status" = { fg = "grey" }

"line_status.modified" = { bg = "purple" }
"line_status.added" = { bg = "green" }
"line_status.deleted" = { bg = "deepRed" }

"prompt.name" = { bg = "grey", decorations = ["bold"] }
"meta_line.background" = { bg = "lightgrey2" }

"finder.input" = { fg = "default" }
"finder.selected" = { fg = "malibu" }

"notification.warn" = { fg = "coral" }
"notification.info" = { fg = "fountainBlue" }
"notification.error" = { fg = "error" }

"flash" = { fg = "whiskey" }

"completion.item" = { bg = "dark" }
"completion.selected" = { bg = "grey" }

[colors]
chalky = "#e5c07b"
coral = "#e06c75"
dark = "#5c6370"
error = "#f44747"
fountainBlue = "#56b6c2"
green = "#98c379"
invalid = "#ffffff"
lightDark = "#7f848e"
lightWhite = "#abb2bf"
malibu = "#61afef"
purple = "#c678dd"
whiskey = "#d19a66"
deepRed = "#BE5046"

default = "default"
grey = "#323232"
lightgrey = "#3a3a3a"
lightgrey2 = "#15155a"
lightgrey3 = "#2545aa"
black = "#111111"
