language: rust
dist: bionic
osx_image: xcode11
cache: cargo

notifications:
  email: false

os:
  - linux
  - osx
  - windows

rust:
  - nightly
  - beta
  - stable

script:
  - cargo build
  - cargo build --release
  - cargo test
