language: rust
dist: bionic
osx_image: xcode11
cache: cargo

notifications:
  email: false

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    # We don't support Windows for now since termion doesn't support it. See:
    # https://gitlab.redox-os.org/redox-os/termion/merge_requests/151
    - os: windows

rust:
  - nightly
  - beta
  - stable

script:
  - cargo build
  - cargo build --release
  - cargo test
