[package]
name = "noa"
version = "0.0.2"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"
description = "A terminal-based text editor (WIP)."
keywords = []
categories = ["text-editors"]
readme = "README.md"
license = "CC0-1.0 OR MIT"
repository = "https://github.com/seiyanuta/noa"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = false

[dependencies]
lazy_static = "1"
log = { version = "^0.4.6", features = ["max_level_trace", "release_max_level_warn"] }
termion = "^1.5.1"
unicode-width = "0"
signal-hook = "0"
dirs = "2"
backtrace = "0"
structopt = "0"
syntect = "3"

[dev-dependencies]
pretty_assertions = "0"
