[package]
name = "noa"
version = "0.0.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]
edition = "2018"
description = "A terminal-based text editor tailored just for me."
keywords = []
categories = ["text-editors"]
readme = "README.md"
license = "CC0-1.0 OR MIT"
repository = "https://github.com/seiyanuta/noa"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = false

[dependencies]
