[package]
name = "noa_buffer"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
ropey = "^1.3.2"

noa_editorconfig = { path = "../editorconfig" }
noa_languages = { path = "../languages" }
